# Grep Filter drops logs that are only whitespace.
# Kubernetes Filter appends K8s information to all outgoing logs.
additionalFilters: |
  [FILTER]
      Name  grep
      Match *
      Regex $log (.|\s)*\S(.|\s)*
  [FILTER]
      Name                nest
      Match               *
      Wildcard            pod_name
      Operation lift
      Nested_under kubernetes
      Add_prefix   eks_
  [FILTER]
      Name                grep
      Match               kube.*
      Exclude             eks_namespace_name kube-system
  [FILTER]
      Name                grep
      Match               kube.*
      Exclude             eks_namespace_name aws-cloudwatch-logs
  [FILTER]
      Name                grep
      Match               kube.*
      Exclude             eks_namespace_name kube-external-secrets
  [FILTER]
      Name                grep
      Match               kube.*
      Exclude             eks_namespace_name kube-node-lease
  [FILTER]
      Name                grep
      Match               kube.*
      Exclude             eks_namespace_name kube-public
