# Grep Filter drops logs that are only whitespace.
# Kubernetes Filter appends K8s information to all outgoing logs.
additionalFilters: |
  [FILTER]
      Name  grep
      Match *
      Regex $log (.|\s)*\S(.|\s)*
  [FILTER]
      Name                nest
      Match               *
      Wildcard            pod_name
      Operation lift
      Nested_under kubernetes
  [FILTER]
      Name                grep
      Match               kube.*
      Exclude             namespace_name kube-system
  [FILTER]
      Name                grep
      Match               kube.*
      Exclude             namespace_name aws-cloudwatch-logs
  [FILTER]
      Name                grep
      Match               kube.*
      Exclude             namespace_name kube-external-secrets
  [FILTER]
      Name                grep
      Match               kube.*
      Exclude             namespace_name kube-node-lease
  [FILTER]
      Name                grep
      Match               kube.*
      Exclude             namespace_name kube-public
  [FILTER]
      Name                grep
      Match               kube.*
      Exclude             namespace_name default
  [FILTER]
      Name                record_modifier
      Match               kube.*
      Remove_key          container_hash
      Remove_key          pod_name
      Remove_key          docker_id
      Remove_key          labels
      Remove_key          annotations
      Remove_key          pod_id
